name: deploy to Cloud Run

on:
  create:
    tags:
    - v*

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: github-action-test
  RUN_REGION: asia-east1

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
        
    # Print gcloud info
    - name: Info
      run: gcloud info

    - name: ls
      run: ls -al

    # Build and push image to Google Artifact Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --tag "asia-east1-docker.pkg.dev/${PROJECT_ID}/$SERVICE_NAME:$GITHUB_SHA" \
          --file ./build/Dockerfile
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --region "$RUN_REGION" \
          --image "asia-east1-docker.pkg.dev/${PROJECT_ID}/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
          
